### ISSUE TITLE
repository docker.io/gnocchi-base not found

### ISSUE THREAD

**Issue by jacobborisov** [gnocchixyz/gnocchi-docker#22]
Hello. 

When I'm trying to set up containers as described in readme, I've got the following output:

```
# docker-compose up
Building gnocchi-metricd
Step 1/7 : FROM gnocchi-base
Trying to pull repository docker.io/library/gnocchi-base ... 
ERROR: Service 'gnocchi-metricd' failed to build: repository docker.io/gnocchi-base not found: does not exist or no pull access
```

Please could you tell me if it a bug in the repo or I simply doing wrong something. Thanks.

**Comment by jd** [comment]
You need to call `./build-base-images.sh` to build the base images. It's in the README.
