### ISSUE TITLE
pip is unable to install psycopg2 as part of gnocchi-base (and uswgi)

### ISSUE THREAD

**Issue by Iridescens** [gnocchixyz/gnocchi-docker#31]
"pip install -U ${package_name}[file,redis,postgresql] uwsgi" in 'gnocchi-docker/base/Dockerfile-gnocchi-base' fails to complete due to unsatisfied dependencies on PostgreSQL.

Solution: (add libpq-dev and python-dev, the latter is a failsafe)

RUN apt-get update && apt-get install -y \
    libpq-dev \
    python-dev \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/* \
    && pip install -U ${package_name}[file,redis,postgresql] uwsgi

**Comment by chungg** [comment]
left off python-dev to keep image to a minimal. let me know if you feel strongly that it should be included
