### ISSUE TITLE
need more documentation

### ISSUE THREAD

**Issue by SaiHarshaK** [gnocchixyz/gnocchi-docker#34]
It doesn't specify the correct number of dockers spwaned(gnocchi spawns two) and that docker-compose-host.yaml and docker-compose-prom.yaml contains the service for collectd and prometheus which got me confused.

**Comment by chungg** [comment]
sorry, i don't use this. care to contribute and update the README file? :)

**Comment by chungg** [comment]
and... ignore my comment.

thanks for the PR!
